[package]
name = "jrnl"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
config = {version = "0.14.1", features = ["toml"]}
xdg = "3.0.0"
